### ISSUE TITLE
Source code request

### ISSUE THREAD

**Issue by Phoenix616** [slushiegoose/Town-Of-Us#20] opened 2021-03-05 02:54 UTC
Is there a place to download the source code from? The repo doesn't seem to include it but it claims to be licensed under GPLv3? Please provide access to it as granted in the license.

**Comment by gendelo3** [comment] 2021-03-05 11:48
you should check the releases, the source code is available as zip file.

**Comment by Phoenix616** [comment] 2021-03-05 12:29
@gendelo3 no it doesn't. It only contains the dll, the mod loader setup and the contents of the repository (which doesn't contain the source)

**Comment by manniL** [comment] 2021-03-05 16:58
Lets merge this issue and #21

**Comment by slushiegoose** [comment] 2021-03-12 13:43
Duplicate of #16

**Closed by slushiegoose** 2021-03-12 13:43 UTC
